/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Container, Row, Col } from "react-bootstrap";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { Configurator } from "@/components/Configurator/Configurator";
import classes from "./Login.module.css";
import {
  Heading,
  Ingress,
  Link,
  Card,
  Paragraph,
  SkipLink,
  Textfield,
  Button,
  Radio,
  Checkbox,
} from "@digdir/design-system-react";
import NextLink from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>Designsystemet - Fokus demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SkipLink href="#main-content">Hopp til hovedinnhold</SkipLink>
      <main className={`${styles.main} ${inter.className}`}>
        <Configurator>
          <div className={classes.container}>
            <div className={classes.form}>
              <Heading size="small">Registerer ny bruker</Heading>

              <Textfield
                description=""
                label="Brukernavn"
                size="medium"
                placeholder="Ola Normann"
              />

              <Textfield
                description=""
                label="Passord"
                size="medium"
                placeholder="ola@gmail.com"
              />

              <Radio.Group
                error=""
                legend="Rolle"
                onChange={function noRefCheck() {}}
                size="medium"
              >
                <Radio value="vanilje">Admin</Radio>
                <Radio value="jordbær">Editor</Radio>
                <Radio value="sjokolade">Subscriber</Radio>
              </Radio.Group>

              <Checkbox size="medium" value="value">
                Abonner på nyhetsbrev
              </Checkbox>

              <Button asChild>
                <NextLink href="/dashboard">Registrer ny bruker</NextLink>
              </Button>
            </div>
          </div>
        </Configurator>
      </main>
    </>
  );
}
