/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Container, Row, Col } from "react-bootstrap";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { Bar } from "@/components/Configurator/Configurator";
import classes from "./Article.module.css";
import {
  Heading,
  Ingress,
  Link,
  Card,
  Paragraph,
} from "@digdir/design-system-react";

const inter = Inter({ subsets: ["latin"] });

export default function Article() {
  return (
    <>
      <Head>
        <title>Designsystemet - Fokus demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Bar />
        <div className={classes.page}>
          <div className={classes.header}>
            <Container>
              <Heading className={classes.heading}>
                Train employees, raised seemed minutes he by distribe
              </Heading>
              <Ingress className={classes.ingress}>
                Rain the even packed, as observed, the text trust however place
                fortune. Great him in seven as made, consideration terms,
                carpeting chosen into him seriously acting the clock, phase
              </Ingress>
            </Container>
          </div>
          <div className={classes.body}>
            <div className={classes.smallBody}>
              <Paragraph>
                Was rippedup, but purpose chequered the stupid taking the fresh
                for too, of the have out kind great participate to disguised he
                such take their wrong dropped his would the would came whats
                their little. Him and which way last is the on its had and
              </Paragraph>

              <Paragraph>
                Was rippedup, but purpose chequered the stupid taking the fresh
                for too, of the have out kind great participate to disguised he
                such take their wrong dropped his would the would came whats
                their little. Him and which way last is the on its had and
              </Paragraph>

              <Paragraph>
                Was rippedup, but purpose chequered the stupid taking the fresh
                for too, of the have out kind great participate to disguised he
                such take their wrong dropped his would the would came whats
                their little. Him and which way last is the on its had and
              </Paragraph>
            </div>
          </div>
        </div>
        Article
      </main>
    </>
  );
}
