/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import classes from "./Dashboard.module.css";
import { Heading } from "@digdir/design-system-react";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { Toolbar } from "@/components/Toolbar/Toolbar";
import { ConfigurationLayout } from "@/layouts/ConfigurationLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Designsystemet - Fokus demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ConfigurationLayout>
          <div className={classes.page}>
            <div className={classes.toolbar}>
              <Toolbar />
            </div>
            <div className={classes.sidebar}>
              <Sidebar />
            </div>
            <div className={classes.main}>
              <div className={classes.left}>
                <Heading size="xsmall">Brukere</Heading>
              </div>
              <div className={classes.right}>
                <Heading size="xsmall">Info</Heading>
              </div>
            </div>
          </div>
        </ConfigurationLayout>
      </main>
    </>
  );
}
